### PR TITLE
Fix search for option aliases in UCI dialects

### LINKED ISSUE #412: Support hashsize in UCCI
I can't set size of hash table in Chinese Xiangqi GUIs I tested. UCCI uses option `hashsize(spin)` instead of `Hash(spin)`.

### PR DESCRIPTION
**Pull request by cloudfish**
Commit b01c9ab does not fix #412, so I tried to debug it. This should fix #412 now.

### CODE REVIEW

**Comment by ianfab** [comment]
Thanks. When I briefly tested it yesterday it seemed to work, but I will re-check. I wanted to avoid using the equality operator in order to consider case insensitivity, but forgot that actually the equality operator anyway already is overriden to consider that, so I guess your solution should be fine.

File: src/uci.cpp [hunk 1]
```diff
@@ -568,7 +568,7 @@ bool UCI::is_valid_option(UCI::OptionsMap& options, std::string& name) {
   std::string protocol = options["Protocol"];
   for (const auto& it : options)
   {
-      if (options.key_comp()(option_name(it.first, protocol), name))
+      if (option_name(it.first, protocol) == name)
```
Comment (ianfab) [inline src/uci.cpp:571]: Since we are comparing strings here and not an Option to a string, we actually have to use the case insensitive less comparator instead of the equality operator in order to avoid having a case sensitive match. I think my version was wrong because the comparator is testing for "less", not for equality. So something like the below should work I think.
```suggestion
      std::string optionName = option_name(it.first, protocol);
      if (!options.key_comp()(optionName, name) && !options.key_comp()(name, optionName))
```
